import "../globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";

import AuthProvider from "@/components/provider/auth-provider";
import Navbar from "@/components/shared/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "reThreads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main className="max-w-xl mx-auto px-6 sm:px-0 flex h-screen justify-center items-center">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
